# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Nidastore' do
    pod 'Alamofire', '~> 3.3.0'
    
    #pod 'Crashlytics'
    #pod 'KeychainAccess', '~> 2.3.5'
    #pod 'Kanna', '~> 1.0.6'
    #pod 'R.swift', '~> 2.1.0'
    #pod 'Static', git: 'https://github.com/venmo/Static'
    #pod 'Toast-Swift', '~> 1.3.0'
end
